<a href="https://colab.research.google.com/github/shouwiz/CampusX/blob/Column-Transformer/ColumnTransfer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
X_train

    age  gender  fever   cough       city
37   55    Male  100.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
48   66    Male   99.0  Strong  Bangalore
44   20    Male  102.0  Strong      Delhi
12   25  Female   99.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
88    5  Female  100.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
53   83    Male   98.0    Mild      Delhi
68   54  Female  104.0  Strong    Kolkata
20   12    Male   98.0  Strong  Bangalore

[80 rows x 5 columns]

#### Normal Scenario

In [6]:
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [7]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [10]:
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [11]:
X_train_age = X_train.drop(columns=['gender','city','fever','cough',])
X_test_age = X_test.drop(columns=['gender','city','fever','cough',])
X_train_age.shape

(80, 1)

#### Column Transformer

In [12]:
from sklearn.compose import ColumnTransformer

In [17]:
transformer = ColumnTransformer(transformers=[('tf1',SimpleImputer(),['fever']),
                                              ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                              ('tf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])],
                                              remainder = 'passthrough')

In [19]:
transformer.fit_transform(X_train).shape

(80, 7)

In [20]:
transformer.transform(X_test).shape

(20, 7)